### ISSUE TITLE
Breadth first Search triple loop

### ISSUE THREAD

**Issue by Shivlock221b** [yixuaz/algorithm4-princeton-cos226#1]
hey, I don't think there is any need for the triple loop in the breadth-first algorithm because the while loop does the work for the first for-loop. If I am wrong please give a small reason why the three loops.

**Comment by yixuaz** [comment]
i think you mentioned is the code in `DiameterAndCenterOfTree`;  while loop **does not** do the work for the first for-loop; the first for-loop handle all the nodes in same distance. without this, we don't know `diameter`, it only ++ after first for-loop; and since  node will be marked seen; so the time complexity is same.
